-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE 'MANAGER';
ALTER TYPE "UserRole" ADD VALUE 'CASHIER';
ALTER TYPE "UserRole" ADD VALUE 'KITCHEN_STAFF';
ALTER TYPE "UserRole" ADD VALUE 'DRIVER';
