import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEnum, IsOptional, IsString } from 'class-validator';
import { UserRole } from '@prisma-app/client';

export class VerifyOtpDto {
  @ApiProperty({
    example: 'eyJhbGciOiJSUzI1NiIs...',
    description: 'Firebase ID token generated by the client after successful SMS verification',
  })
  @IsString()
  firebaseToken: string;

  @ApiPropertyOptional({
    enum: UserRole,
    default: UserRole.CUSTOMER,
    description: 'Applied only when the phone is not registered yet',
  })
  @IsOptional()
  @IsEnum(UserRole)
  role?: UserRole;
}
