name: QuickBite - Local
values:
  - key: base_url
    value: 'http://localhost:3000'
  - key: restaurant_url
    value: 'http://localhost:3001'
  - key: order_url
    value: 'http://localhost:3002'
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: restaurant_id
    value: ''
  - key: menu_item_id
    value: ''
  - key: category_id
    value: ''
  - key: order_id
    value: ''
